name: testContracts

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - contract/**

jobs:
  contractTester:
    runs-on: ubuntu-latest
    env:
      working-directory: ./contract

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: debug
        run: |
          ls -al
          pwd
          
      - name: Install node packages
        run: npm install

      - name: Install ganache-cli
        run: npm install -g ganache-cli

      - name: Launch ganache-cli network
        run: ganache-cli &

      - name: Test with Truffle test
        run: truffle test --network local
